/*
-- Query: SELECT * FROM gdb0041.dim_customer
LIMIT 0, 1000

-- Date: 2026-07-11 22:48
*/
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70002017,'Atliq Exclusive','Brick & Mortar','Direct','India','India','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70002018,'Atliq e Store','E-Commerce','Direct','India','India','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70003181,'Atliq Exclusive','Brick & Mortar','Direct','Indonesia','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70003182,'Atliq e Store','E-Commerce','Direct','Indonesia','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70004069,'Atliq Exclusive','Brick & Mortar','Direct','Japan','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70004070,'Atliq e Store','E-Commerce','Direct','Japan','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70005163,'Atliq e Store','E-Commerce','Direct','Pakistan','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70006157,'Atliq Exclusive','Brick & Mortar','Direct','Philiphines','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70006158,'Atliq e Store','E-Commerce','Direct','Philiphines','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70007198,'Atliq Exclusive','Brick & Mortar','Direct','South Korea','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70007199,'Atliq e Store','E-Commerce','Direct','South Korea','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70008169,'Atliq Exclusive','Brick & Mortar','Direct','Australia','ANZ','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70008170,'Atliq e Store','E-Commerce','Direct','Australia','ANZ','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70009133,'Atliq Exclusive','Brick & Mortar','Direct','Newzealand','ANZ','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70009134,'Atliq e Store','E-Commerce','Direct','Newzealand','ANZ','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70010047,'Atliq Exclusive','Brick & Mortar','Direct','Bangladesh','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70010048,'Atliq e Store','E-Commerce','Direct','Bangladesh','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70011193,'Atliq Exclusive','Brick & Mortar','Direct','France','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70011194,'Atliq e Store','E-Commerce','Direct','France','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70012042,'Atliq Exclusive','Brick & Mortar','Direct','Germany','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70012043,'Atliq e Store','E-Commerce','Direct','Germany','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70013125,'Atliq Exclusive','Brick & Mortar','Direct','Italy','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70013126,'Atliq e Store','E-Commerce','Direct','Italy','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70014142,'Atliq Exclusive','Brick & Mortar','Direct','Netherlands','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70014143,'Atliq e Store','E-Commerce','Direct','Netherlands','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70015151,'Atliq Exclusive','Brick & Mortar','Direct','Norway','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70015152,'Atliq e Store','E-Commerce','Direct','Norway','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70016177,'Atliq Exclusive','Brick & Mortar','Direct','Poland','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70016178,'Atliq e Store','E-Commerce','Direct','Poland','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70017060,'Atliq e Store','E-Commerce','Direct','Portugal','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70018115,'Atliq e Store','E-Commerce','Direct','Spain','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70019204,'Atliq e Store','E-Commerce','Direct','Sweden','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70020104,'Atliq e Store','E-Commerce','Direct','Austria','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70021096,'Atliq e Store','E-Commerce','Direct','United Kingdom','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70022084,'Atliq Exclusive','Brick & Mortar','Direct','USA','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70022085,'Atliq e Store','E-Commerce','Direct','USA','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70023031,'Atliq Exclusive','Brick & Mortar','Direct','Canada','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70023032,'Atliq e Store','E-Commerce','Direct','Canada','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70026206,'Atliq e Store','E-Commerce','Direct','Mexico','LATAM','LATAM');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (70027208,'Atliq e Store','E-Commerce','Direct','Brazil','LATAM','LATAM');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (80001019,'Neptune','Brick & Mortar','Distributor','China','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (80006154,'Synthetic','Brick & Mortar','Distributor','Philiphines','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (80006155,'Novus','Brick & Mortar','Distributor','Philiphines','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (80007195,'Sage','Brick & Mortar','Distributor','South Korea','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (80007196,'Leader','Brick & Mortar','Distributor','South Korea','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90001020,'Zone','Brick & Mortar','Retailer','China','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90001021,'Taobao','E-Commerce','Retailer','China','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90002001,'Reliance Digital','Brick & Mortar','Retailer','India','India','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90002002,'Croma','Brick & Mortar','Retailer','India','India','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90002003,'Ezone','Brick & Mortar','Retailer','India','India','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90002004,'Vijay Sales','Brick & Mortar','Retailer','India','India','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90002005,'Lotus','Brick & Mortar','Retailer','India','India','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90002006,'Viveks','Brick & Mortar','Retailer','India','India','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90002007,'Girias','Brick & Mortar','Retailer','India','India','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90002008,'Amazon','E-Commerce','Retailer','India','India','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90002009,'Flipkart','E-Commerce','Retailer','India','India','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90002010,'Ebay','E-Commerce','Retailer','India','India','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90002011,'Atliq Exclusive','Brick & Mortar','Retailer','India','India','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90002012,'Electricalsocity','Brick & Mortar','Retailer','India','India','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90002013,'Electricalslytical','Brick & Mortar','Retailer','India','India','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90002014,'Expression','Brick & Mortar','Retailer','India','India','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90002015,'Propel','Brick & Mortar','Retailer','India','India','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90002016,'Amazon ','E-Commerce','Retailer','India','India','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90003179,'Acclaimed Stores','Brick & Mortar','Retailer','Indonesia','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90003180,'Amazon ','E-Commerce','Retailer','Indonesia','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90004061,'Info Stores','Brick & Mortar','Retailer','Japan','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90004062,'Flawless Stores','Brick & Mortar','Retailer','Japan','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90004063,'Electricalsbea Stores','Brick & Mortar','Retailer','Japan','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90004064,'All-Out','Brick & Mortar','Retailer','Japan','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90004065,'Neptune','Brick & Mortar','Retailer','Japan','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90004066,'Surface Stores','Brick & Mortar','Retailer','Japan','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90004067,'Amazon','E-Commerce','Retailer','Japan','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90004068,'Amazon ','E-Commerce','Retailer','Japan','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90005159,'Expression','Brick & Mortar','Retailer','Pakistan','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90005160,'Nomad Stores','Brick & Mortar','Retailer','Pakistan','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90005161,'Zone','Brick & Mortar','Retailer','Pakistan','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90005162,'Amazon ','E-Commerce','Retailer','Pakistan','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90006153,'Insight','Brick & Mortar','Retailer','Philiphines','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90006156,'Amazon ','E-Commerce','Retailer','Philiphines','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90007197,'Amazon ','E-Commerce','Retailer','South Korea','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90008164,'Digimarket','Brick & Mortar','Retailer','Australia','ANZ','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90008165,'Forward Stores','Brick & Mortar','Retailer','Australia','ANZ','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90008166,'Sound','Brick & Mortar','Retailer','Australia','ANZ','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90008167,'Electricalsocity','Brick & Mortar','Retailer','Australia','ANZ','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90008168,'Amazon ','E-Commerce','Retailer','Australia','ANZ','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90009127,'Epic Stores','Brick & Mortar','Retailer','Newzealand','ANZ','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90009128,'Propel','Brick & Mortar','Retailer','Newzealand','ANZ','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90009129,'Leader','Brick & Mortar','Retailer','Newzealand','ANZ','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90009130,'Logic Stores','Brick & Mortar','Retailer','Newzealand','ANZ','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90009131,'Path','Brick & Mortar','Retailer','Newzealand','ANZ','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90009132,'Amazon ','E-Commerce','Retailer','Newzealand','ANZ','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90010044,'Surface Stores','Brick & Mortar','Retailer','Bangladesh','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90010045,'Control','Brick & Mortar','Retailer','Bangladesh','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90010046,'Amazon ','E-Commerce','Retailer','Bangladesh','ROA','APAC');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90011185,'Epic Stores','Brick & Mortar','Retailer','France','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90011186,'Elite','Brick & Mortar','Retailer','France','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90011187,'Chip 7','Brick & Mortar','Retailer','France','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90011188,'Elkjøp','Brick & Mortar','Retailer','France','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90011189,'UniEuro','Brick & Mortar','Retailer','France','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90011190,'Media Markt','Brick & Mortar','Retailer','France','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90011191,'Sorefoz','Brick & Mortar','Retailer','France','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90011192,'Amazon ','E-Commerce','Retailer','France','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90012033,'Digimarket','Brick & Mortar','Retailer','Germany','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90012034,'Otto','Brick & Mortar','Retailer','Germany','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90012035,'Notebillig','Brick & Mortar','Retailer','Germany','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90012036,'Billa','Brick & Mortar','Retailer','Germany','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90012037,'Saturn','Brick & Mortar','Retailer','Germany','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90012038,'Expert','Brick & Mortar','Retailer','Germany','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90012039,'Currys (Dixons Carphone)','Brick & Mortar','Retailer','Germany','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90012040,'Fnac-Darty','Brick & Mortar','Retailer','Germany','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90012041,'Amazon ','E-Commerce','Retailer','Germany','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90013116,'Unity Stores','Brick & Mortar','Retailer','Italy','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90013117,'Euronics','Brick & Mortar','Retailer','Italy','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90013118,'Fnac-Darty','Brick & Mortar','Retailer','Italy','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90013119,'Argos (Sainsbury\'s)','Brick & Mortar','Retailer','Italy','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90013120,'Coolblue','Brick & Mortar','Retailer','Italy','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90013121,'Boulanger','Brick & Mortar','Retailer','Italy','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90013122,'Radio Popular','Brick & Mortar','Retailer','Italy','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90013123,'Expert','Brick & Mortar','Retailer','Italy','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90013124,'Amazon ','E-Commerce','Retailer','Italy','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90014135,'Electricalslance Stores','Brick & Mortar','Retailer','Netherlands','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90014136,'Reliance Digital','Brick & Mortar','Retailer','Netherlands','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90014137,'Media Markt','Brick & Mortar','Retailer','Netherlands','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90014138,'Mbit','Brick & Mortar','Retailer','Netherlands','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90014139,'Elkjøp','Brick & Mortar','Retailer','Netherlands','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90014140,'Radio Popular','Brick & Mortar','Retailer','Netherlands','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90014141,'Amazon ','E-Commerce','Retailer','Netherlands','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90015144,'Sound','Brick & Mortar','Retailer','Norway','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90015145,'Synthetic','Brick & Mortar','Retailer','Norway','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90015146,'Mbit','Brick & Mortar','Retailer','Norway','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90015147,'Chiptec','Brick & Mortar','Retailer','Norway','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90015148,'Boulanger','Brick & Mortar','Retailer','Norway','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90015149,'UniEuro','Brick & Mortar','Retailer','Norway','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90015150,'Amazon ','E-Commerce','Retailer','Norway','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90016171,'Electricalsara Stores','Brick & Mortar','Retailer','Poland','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90016172,'Power','Brick & Mortar','Retailer','Poland','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90016173,'Expert','Brick & Mortar','Retailer','Poland','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90016174,'Currys (Dixons Carphone)','Brick & Mortar','Retailer','Poland','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90016175,'Argos (Sainsbury\'s)','Brick & Mortar','Retailer','Poland','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90016176,'Amazon ','E-Commerce','Retailer','Poland','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90017049,'Premium Stores','Brick & Mortar','Retailer','Portugal','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90017050,'Electricalsara Stores','Brick & Mortar','Retailer','Portugal','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90017051,'Forward Stores','Brick & Mortar','Retailer','Portugal','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90017052,'Power','Brick & Mortar','Retailer','Portugal','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90017053,'Info Stores','Brick & Mortar','Retailer','Portugal','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90017054,'Flawless Stores','Brick & Mortar','Retailer','Portugal','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90017055,'Electricalslance Stores','Brick & Mortar','Retailer','Portugal','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90017056,'Sorefoz','Brick & Mortar','Retailer','Portugal','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90017057,'Euronics','Brick & Mortar','Retailer','Portugal','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90017058,'Mbit','Brick & Mortar','Retailer','Portugal','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90017059,'Amazon ','E-Commerce','Retailer','Portugal','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90018105,'Integration Stores','Brick & Mortar','Retailer','Spain','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90018106,'Flipkart','E-Commerce','Retailer','Spain','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90018107,'Elite','Brick & Mortar','Retailer','Spain','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90018108,'Relief','Brick & Mortar','Retailer','Spain','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90018109,'Chiptec','Brick & Mortar','Retailer','Spain','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90018110,'Boulanger','Brick & Mortar','Retailer','Spain','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90018111,'Media Markt','Brick & Mortar','Retailer','Spain','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90018112,'Euronics','Brick & Mortar','Retailer','Spain','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90018113,'Elkjøp','Brick & Mortar','Retailer','Spain','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90018114,'Amazon ','E-Commerce','Retailer','Spain','SE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90019200,'Sorefoz','Brick & Mortar','Retailer','Sweden','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90019201,'Expert','Brick & Mortar','Retailer','Sweden','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90019202,'Argos (Sainsbury\'s)','Brick & Mortar','Retailer','Sweden','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90019203,'Amazon ','E-Commerce','Retailer','Sweden','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90020097,'Atlas Stores','Brick & Mortar','Retailer','Austria','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90020098,'Electricalsquipo Stores','Brick & Mortar','Retailer','Austria','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90020099,'Integration Stores','Brick & Mortar','Retailer','Austria','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90020100,'Nova','Brick & Mortar','Retailer','Austria','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90020101,'Euronics','Brick & Mortar','Retailer','Austria','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90020102,'Fnac-Darty','Brick & Mortar','Retailer','Austria','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90020103,'Amazon ','E-Commerce','Retailer','Austria','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90021086,'Electricalsquipo Stores','Brick & Mortar','Retailer','United Kingdom','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90021087,'Logic Stores','Brick & Mortar','Retailer','United Kingdom','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90021088,'Electricalslytical','Brick & Mortar','Retailer','United Kingdom','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90021089,'Atlas Stores','Brick & Mortar','Retailer','United Kingdom','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90021090,'Radio Popular','Brick & Mortar','Retailer','United Kingdom','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90021091,'Expert','Brick & Mortar','Retailer','United Kingdom','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90021092,'UniEuro','Brick & Mortar','Retailer','United Kingdom','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90021093,'Chip 7','Brick & Mortar','Retailer','United Kingdom','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90021094,'Coolblue','Brick & Mortar','Retailer','United Kingdom','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90021095,'Amazon ','E-Commerce','Retailer','United Kingdom','NE','EU');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90022071,'Acclaimed Stores','Brick & Mortar','Retailer','USA','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90022072,'Path','Brick & Mortar','Retailer','USA','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90022073,'Control','Brick & Mortar','Retailer','USA','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90022074,'Flipkart','E-Commerce','Retailer','USA','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90022075,'BestBuy','Brick & Mortar','Retailer','USA','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90022076,'Circuit City','Brick & Mortar','Retailer','USA','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90022077,'Radio Shack','Brick & Mortar','Retailer','USA','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90022078,'Costco','Brick & Mortar','Retailer','USA','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90022079,'walmart','Brick & Mortar','Retailer','USA','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90022080,'Staples','Brick & Mortar','Retailer','USA','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90022081,'Amazon','E-Commerce','Retailer','USA','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90022082,'Amazon ','E-Commerce','Retailer','USA','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90022083,'Ebay','E-Commerce','Retailer','USA','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90023022,'Nomad Stores','Brick & Mortar','Retailer','Canada','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90023023,'Amazon','E-Commerce','Retailer','Canada','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90023024,'Sage','Brick & Mortar','Retailer','Canada','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90023025,'Premium Stores','Brick & Mortar','Retailer','Canada','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90023026,'Relief','Brick & Mortar','Retailer','Canada','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90023027,'Costco','Brick & Mortar','Retailer','Canada','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90023028,'walmart','Brick & Mortar','Retailer','Canada','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90023029,'Staples','Brick & Mortar','Retailer','Canada','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90023030,'Amazon ','E-Commerce','Retailer','Canada','NA','NA');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90024183,'Electricalsbea Stores','Brick & Mortar','Retailer','Chile','LATAM','LATAM');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90024184,'Amazon ','E-Commerce','Retailer','Chile','LATAM','LATAM');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90025209,'Electricalsbea Stores','Brick & Mortar','Retailer','Columbia','LATAM','LATAM');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90026205,'Amazon ','E-Commerce','Retailer','Mexico','LATAM','LATAM');
INSERT INTO `` (`customer_code`,`customer`,`platform`,`channel`,`market`,`sub_zone`,`region`) VALUES (90027207,'Amazon ','E-Commerce','Retailer','Brazil','LATAM','LATAM');
