/*
-- Query: SELECT * FROM gdb0041.dim_product
LIMIT 0, 1000

-- Date: 2026-07-11 22:50
*/
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0118150101','P & A','Peripherals','Internal HDD','AQ Dracula HDD – 3.5 Inch SATA 6 Gb/s 5400 RPM 256 MB Cache','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0118150102','P & A','Peripherals','Internal HDD','AQ Dracula HDD – 3.5 Inch SATA 6 Gb/s 5400 RPM 256 MB Cache','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0118150103','P & A','Peripherals','Internal HDD','AQ Dracula HDD – 3.5 Inch SATA 6 Gb/s 5400 RPM 256 MB Cache','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0118150104','P & A','Peripherals','Internal HDD','AQ Dracula HDD – 3.5 Inch SATA 6 Gb/s 5400 RPM 256 MB Cache','Premium Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0219150201','P & A','Peripherals','Internal HDD','AQ WereWolf NAS Internal Hard Drive HDD – 8.89 cm','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0219150202','P & A','Peripherals','Internal HDD','AQ WereWolf NAS Internal Hard Drive HDD – 8.89 cm','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0220150203','P & A','Peripherals','Internal HDD','AQ WereWolf NAS Internal Hard Drive HDD – 8.89 cm','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0320150301','P & A','Peripherals','Internal HDD','AQ Zion Saga','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0321150302','P & A','Peripherals','Internal HDD','AQ Zion Saga','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0321150303','P & A','Peripherals','Internal HDD','AQ Zion Saga','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0418150101','P & A','Peripherals','Graphic Card','AQ Mforce Gen X','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0418150102','P & A','Peripherals','Graphic Card','AQ Mforce Gen X','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0418150103','P & A','Peripherals','Graphic Card','AQ Mforce Gen X','Standard 3');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0418150104','P & A','Peripherals','Graphic Card','AQ Mforce Gen X','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0418150105','P & A','Peripherals','Graphic Card','AQ Mforce Gen X','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0418150106','P & A','Peripherals','Graphic Card','AQ Mforce Gen X','Plus 3');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0418150107','P & A','Peripherals','Graphic Card','AQ Mforce Gen X','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0418150108','P & A','Peripherals','Graphic Card','AQ Mforce Gen X','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0519150201','P & A','Peripherals','Graphic Card','AQ Mforce Gen Y','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0519150202','P & A','Peripherals','Graphic Card','AQ Mforce Gen Y','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0519150203','P & A','Peripherals','Graphic Card','AQ Mforce Gen Y','Standard 3');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0519150204','P & A','Peripherals','Graphic Card','AQ Mforce Gen Y','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0519150205','P & A','Peripherals','Graphic Card','AQ Mforce Gen Y','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0519150206','P & A','Peripherals','Graphic Card','AQ Mforce Gen Y','Plus 3');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0519150207','P & A','Peripherals','Graphic Card','AQ Mforce Gen Y','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0519150208','P & A','Peripherals','Graphic Card','AQ Mforce Gen Y','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0619150301','P & A','Peripherals','Graphic Card','AQ Mforce Gen Z','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0619150302','P & A','Peripherals','Graphic Card','AQ Mforce Gen Z','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0620150303','P & A','Peripherals','Graphic Card','AQ Mforce Gen Z','Standard 3');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0620150304','P & A','Peripherals','Graphic Card','AQ Mforce Gen Z','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0620150305','P & A','Peripherals','Graphic Card','AQ Mforce Gen Z','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0620150306','P & A','Peripherals','Graphic Card','AQ Mforce Gen Z','Plus 3');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0621150307','P & A','Peripherals','Graphic Card','AQ Mforce Gen Z','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0621150308','P & A','Peripherals','Graphic Card','AQ Mforce Gen Z','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0721150401','P & A','Peripherals','Graphic Card','AQ GT 21','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0721150402','P & A','Peripherals','Graphic Card','AQ GT 21','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0721150403','P & A','Peripherals','Graphic Card','AQ GT 21','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0721150404','P & A','Peripherals','Graphic Card','AQ GT 21','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0821150501','P & A','Peripherals','Graphic Card','AQ Marquee P3','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0821150502','P & A','Peripherals','Graphic Card','AQ Marquee P3','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0821150503','P & A','Peripherals','Graphic Card','AQ Marquee P3','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0821150504','P & A','Peripherals','Graphic Card','AQ Marquee P3','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0921150601','P & A','Peripherals','Graphic Card','AQ Marquee P4','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0921150602','P & A','Peripherals','Graphic Card','AQ Marquee P4','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0921150603','P & A','Peripherals','Graphic Card','AQ Marquee P4','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A0921150604','P & A','Peripherals','Graphic Card','AQ Marquee P4','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1018150101','P & A','Peripherals','Processors','AQ 5000 Series Electron 9 5900X Desktop Processor','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1018150102','P & A','Peripherals','Processors','AQ 5000 Series Electron 9 5900X Desktop Processor','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1018150103','P & A','Peripherals','Processors','AQ 5000 Series Electron 9 5900X Desktop Processor','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1118150201','P & A','Peripherals','Processors','AQ 5000 Series Electron 8 5900X Desktop Processor','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1118150202','P & A','Peripherals','Processors','AQ 5000 Series Electron 8 5900X Desktop Processor','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1119150203','P & A','Peripherals','Processors','AQ 5000 Series Electron 8 5900X Desktop Processor','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1219150301','P & A','Peripherals','Processors','AQ 5000 Series Ultron 8 5900X Desktop Processor','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1219150302','P & A','Peripherals','Processors','AQ 5000 Series Ultron 8 5900X Desktop Processor','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1219150303','P & A','Peripherals','Processors','AQ 5000 Series Ultron 8 5900X Desktop Processor','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1319150401','P & A','Peripherals','Processors','AQ Electron 5 3600 Desktop Processor','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1320150402','P & A','Peripherals','Processors','AQ Electron 5 3600 Desktop Processor','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1320150403','P & A','Peripherals','Processors','AQ Electron 5 3600 Desktop Processor','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1420150501','P & A','Peripherals','Processors','AQ Electron 4 3600 Desktop Processor','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1420150502','P & A','Peripherals','Processors','AQ Electron 4 3600 Desktop Processor','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1421150503','P & A','Peripherals','Processors','AQ Electron 4 3600 Desktop Processor','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1521150601','P & A','Peripherals','Processors','AQ Electron 3 3600 Desktop Processor','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1521150602','P & A','Peripherals','Processors','AQ Electron 3 3600 Desktop Processor','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1521150603','P & A','Peripherals','Processors','AQ Electron 3 3600 Desktop Processor','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1618150101','P & A','Peripherals','MotherBoard','AQ MB Elite','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1618150102','P & A','Peripherals','MotherBoard','AQ MB Elite','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1618150103','P & A','Peripherals','MotherBoard','AQ MB Elite','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1618150104','P & A','Peripherals','MotherBoard','AQ MB Elite','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1718150201','P & A','Peripherals','MotherBoard','AQ MB Crossx','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1718150202','P & A','Peripherals','MotherBoard','AQ MB Crossx','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1718150203','P & A','Peripherals','MotherBoard','AQ MB Crossx','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1718150204','P & A','Peripherals','MotherBoard','AQ MB Crossx','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1819150301','P & A','Peripherals','MotherBoard','AQ MB Crossx 2','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1819150302','P & A','Peripherals','MotherBoard','AQ MB Crossx 2','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1819150303','P & A','Peripherals','MotherBoard','AQ MB Crossx 2','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1819150304','P & A','Peripherals','MotherBoard','AQ MB Crossx 2','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1919150401','P & A','Peripherals','MotherBoard','AQ MB Lito','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1919150402','P & A','Peripherals','MotherBoard','AQ MB Lito','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1919150403','P & A','Peripherals','MotherBoard','AQ MB Lito','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A1920150404','P & A','Peripherals','MotherBoard','AQ MB Lito','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2020150501','P & A','Peripherals','MotherBoard','AQ MB Lito 2','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2020150502','P & A','Peripherals','MotherBoard','AQ MB Lito 2','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2021150503','P & A','Peripherals','MotherBoard','AQ MB Lito 2','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2021150504','P & A','Peripherals','MotherBoard','AQ MB Lito 2','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2118150101','P & A','Accessories','Mouse','AQ Master wired x1 Ms','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2118150102','P & A','Accessories','Mouse','AQ Master wired x1 Ms','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2118150103','P & A','Accessories','Mouse','AQ Master wired x1 Ms','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2118150104','P & A','Accessories','Mouse','AQ Master wired x1 Ms','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2118150105','P & A','Accessories','Mouse','AQ Master wired x1 Ms','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2118150106','P & A','Accessories','Mouse','AQ Master wired x1 Ms','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2218150201','P & A','Accessories','Mouse','AQ Master wireless x1 Ms','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2218150202','P & A','Accessories','Mouse','AQ Master wireless x1 Ms','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2219150203','P & A','Accessories','Mouse','AQ Master wireless x1 Ms','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2219150204','P & A','Accessories','Mouse','AQ Master wireless x1 Ms','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2219150205','P & A','Accessories','Mouse','AQ Master wireless x1 Ms','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2219150206','P & A','Accessories','Mouse','AQ Master wireless x1 Ms','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2319150301','P & A','Accessories','Mouse','AQ Gamers Ms','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2319150302','P & A','Accessories','Mouse','AQ Gamers Ms','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2319150303','P & A','Accessories','Mouse','AQ Gamers Ms','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2319150304','P & A','Accessories','Mouse','AQ Gamers Ms','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2319150305','P & A','Accessories','Mouse','AQ Gamers Ms','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2319150306','P & A','Accessories','Mouse','AQ Gamers Ms','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2419150401','P & A','Accessories','Mouse','AQ Lite Ms','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2419150402','P & A','Accessories','Mouse','AQ Lite Ms','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2419150403','P & A','Accessories','Mouse','AQ Lite Ms','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2419150404','P & A','Accessories','Mouse','AQ Lite Ms','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2419150405','P & A','Accessories','Mouse','AQ Lite Ms','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2420150406','P & A','Accessories','Mouse','AQ Lite Ms','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2520150501','P & A','Accessories','Mouse','AQ Maxima Ms','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2520150502','P & A','Accessories','Mouse','AQ Maxima Ms','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2520150503','P & A','Accessories','Mouse','AQ Maxima Ms','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2520150504','P & A','Accessories','Mouse','AQ Maxima Ms','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2520150505','P & A','Accessories','Mouse','AQ Maxima Ms','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2520150506','P & A','Accessories','Mouse','AQ Maxima Ms','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2620150601','P & A','Accessories','Mouse','AQ Qwerty Ms','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2620150602','P & A','Accessories','Mouse','AQ Qwerty Ms','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2620150603','P & A','Accessories','Mouse','AQ Qwerty Ms','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2620150604','P & A','Accessories','Mouse','AQ Qwerty Ms','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2620150605','P & A','Accessories','Mouse','AQ Qwerty Ms','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2620150606','P & A','Accessories','Mouse','AQ Qwerty Ms','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2720150701','P & A','Accessories','Mouse','AQ Trigger Ms','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2721150702','P & A','Accessories','Mouse','AQ Trigger Ms','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2721150703','P & A','Accessories','Mouse','AQ Trigger Ms','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2721150704','P & A','Accessories','Mouse','AQ Trigger Ms','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2721150705','P & A','Accessories','Mouse','AQ Trigger Ms','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2721150706','P & A','Accessories','Mouse','AQ Trigger Ms','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2821150801','P & A','Accessories','Mouse','AQ Lumina Ms','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2821150802','P & A','Accessories','Mouse','AQ Lumina Ms','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2821150803','P & A','Accessories','Mouse','AQ Lumina Ms','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2821150804','P & A','Accessories','Mouse','AQ Lumina Ms','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2821150805','P & A','Accessories','Mouse','AQ Lumina Ms','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2821150806','P & A','Accessories','Mouse','AQ Lumina Ms','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2918150101','P & A','Accessories','Keyboard','AQ Master wired x1','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2918150102','P & A','Accessories','Keyboard','AQ Master wired x1','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2918150103','P & A','Accessories','Keyboard','AQ Master wired x1','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2918150104','P & A','Accessories','Keyboard','AQ Master wired x1','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2918150105','P & A','Accessories','Keyboard','AQ Master wired x1','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A2918150106','P & A','Accessories','Keyboard','AQ Master wired x1','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3018150201','P & A','Accessories','Keyboard','AQ Master wireless x1','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3018150202','P & A','Accessories','Keyboard','AQ Master wireless x1','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3018150203','P & A','Accessories','Keyboard','AQ Master wireless x1','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3019150204','P & A','Accessories','Keyboard','AQ Master wireless x1','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3019150205','P & A','Accessories','Keyboard','AQ Master wireless x1','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3019150206','P & A','Accessories','Keyboard','AQ Master wireless x1','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3119150301','P & A','Accessories','Keyboard','AQ Gamers ','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3119150302','P & A','Accessories','Keyboard','AQ Gamers ','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3119150303','P & A','Accessories','Keyboard','AQ Gamers ','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3120150304','P & A','Accessories','Keyboard','AQ Gamers ','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3120150305','P & A','Accessories','Keyboard','AQ Gamers ','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3120150306','P & A','Accessories','Keyboard','AQ Gamers ','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3220150401','P & A','Accessories','Keyboard','AQ Lite','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3220150402','P & A','Accessories','Keyboard','AQ Lite','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3220150403','P & A','Accessories','Keyboard','AQ Lite','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3220150404','P & A','Accessories','Keyboard','AQ Lite','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3220150405','P & A','Accessories','Keyboard','AQ Lite','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3220150406','P & A','Accessories','Keyboard','AQ Lite','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3320150501','P & A','Accessories','Keyboard','AQ Maxima','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3320150502','P & A','Accessories','Keyboard','AQ Maxima','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3320150503','P & A','Accessories','Keyboard','AQ Maxima','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3320150504','P & A','Accessories','Keyboard','AQ Maxima','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3320150505','P & A','Accessories','Keyboard','AQ Maxima','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3320150506','P & A','Accessories','Keyboard','AQ Maxima','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3420150601','P & A','Accessories','Keyboard','AQ Qwerty','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3420150602','P & A','Accessories','Keyboard','AQ Qwerty','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3421150603','P & A','Accessories','Keyboard','AQ Qwerty','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3421150604','P & A','Accessories','Keyboard','AQ Qwerty','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3421150605','P & A','Accessories','Keyboard','AQ Qwerty','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3421150606','P & A','Accessories','Keyboard','AQ Qwerty','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3521150701','P & A','Accessories','Keyboard','AQ Trigger','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3521150702','P & A','Accessories','Keyboard','AQ Trigger','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3521150703','P & A','Accessories','Keyboard','AQ Trigger','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3521150704','P & A','Accessories','Keyboard','AQ Trigger','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3521150705','P & A','Accessories','Keyboard','AQ Trigger','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3521150706','P & A','Accessories','Keyboard','AQ Trigger','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3621150801','P & A','Accessories','Keyboard','AQ Lumina','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3621150802','P & A','Accessories','Keyboard','AQ Lumina','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3621150803','P & A','Accessories','Keyboard','AQ Lumina','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3621150804','P & A','Accessories','Keyboard','AQ Lumina','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3621150805','P & A','Accessories','Keyboard','AQ Lumina','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3621150806','P & A','Accessories','Keyboard','AQ Lumina','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3718150101','P & A','Accessories','Batteries','AQ LION x1','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3718150102','P & A','Accessories','Batteries','AQ LION x1','Plus 1 ');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3718150103','P & A','Accessories','Batteries','AQ LION x1','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3718150104','P & A','Accessories','Batteries','AQ LION x1','Plus 3');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3718150105','P & A','Accessories','Batteries','AQ LION x1','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3818150201','P & A','Accessories','Batteries','AQ LION x2','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3818150202','P & A','Accessories','Batteries','AQ LION x2','Plus 1 ');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3819150203','P & A','Accessories','Batteries','AQ LION x2','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3819150204','P & A','Accessories','Batteries','AQ LION x2','Plus 3');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3819150205','P & A','Accessories','Batteries','AQ LION x2','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3920150301','P & A','Accessories','Batteries','AQ LION x3','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3920150302','P & A','Accessories','Batteries','AQ LION x3','Plus 1 ');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3920150303','P & A','Accessories','Batteries','AQ LION x3','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3920150304','P & A','Accessories','Batteries','AQ LION x3','Plus 3');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A3920150305','P & A','Accessories','Batteries','AQ LION x3','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4020150401','P & A','Accessories','Batteries','AQ Mx NB','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4020150402','P & A','Accessories','Batteries','AQ Mx NB','Plus 1 ');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4021150403','P & A','Accessories','Batteries','AQ Mx NB','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4021150404','P & A','Accessories','Batteries','AQ Mx NB','Plus 3');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4021150405','P & A','Accessories','Batteries','AQ Mx NB','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4118110101','PC','Notebook','Personal Laptop','AQ Aspiron','Standard Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4118110102','PC','Notebook','Personal Laptop','AQ Aspiron','Standard Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4118110103','PC','Notebook','Personal Laptop','AQ Aspiron','Standard Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4118110104','PC','Notebook','Personal Laptop','AQ Aspiron','Plus Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4118110105','PC','Notebook','Personal Laptop','AQ Aspiron','Plus Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4118110106','PC','Notebook','Personal Laptop','AQ Aspiron','Plus Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4118110107','PC','Notebook','Personal Laptop','AQ Aspiron','Premium Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4218110201','PC','Notebook','Personal Laptop','AQ Digit','Standard Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4218110202','PC','Notebook','Personal Laptop','AQ Digit','Standard Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4218110203','PC','Notebook','Personal Laptop','AQ Digit','Standard Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4218110204','PC','Notebook','Personal Laptop','AQ Digit','Plus Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4218110205','PC','Notebook','Personal Laptop','AQ Digit','Plus Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4218110206','PC','Notebook','Personal Laptop','AQ Digit','Plus Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4218110207','PC','Notebook','Personal Laptop','AQ Digit','Premium Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4218110208','PC','Notebook','Personal Laptop','AQ Digit','Premium Misty Green');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4318110301','PC','Notebook','Personal Laptop','AQ Velocity','Standard Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4319110302','PC','Notebook','Personal Laptop','AQ Velocity','Standard Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4319110303','PC','Notebook','Personal Laptop','AQ Velocity','Standard Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4319110304','PC','Notebook','Personal Laptop','AQ Velocity','Plus Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4319110305','PC','Notebook','Personal Laptop','AQ Velocity','Plus Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4319110306','PC','Notebook','Personal Laptop','AQ Velocity','Plus Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4419110401','PC','Notebook','Personal Laptop','AQ Elite','Standard Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4419110402','PC','Notebook','Personal Laptop','AQ Elite','Standard Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4419110403','PC','Notebook','Personal Laptop','AQ Elite','Standard Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4419110404','PC','Notebook','Personal Laptop','AQ Elite','Plus Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4419110405','PC','Notebook','Personal Laptop','AQ Elite','Plus Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4419110406','PC','Notebook','Personal Laptop','AQ Elite','Plus Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4419110407','PC','Notebook','Personal Laptop','AQ Elite','Premium Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4419110408','PC','Notebook','Personal Laptop','AQ Elite','Premium Misty Green');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4519110501','PC','Notebook','Personal Laptop','AQ Gen X','Standard Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4519110502','PC','Notebook','Personal Laptop','AQ Gen X','Standard Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4519110503','PC','Notebook','Personal Laptop','AQ Gen X','Standard Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4520110504','PC','Notebook','Personal Laptop','AQ Gen X','Plus Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4520110505','PC','Notebook','Personal Laptop','AQ Gen X','Plus Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4520110506','PC','Notebook','Personal Laptop','AQ Gen X','Plus Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4520110507','PC','Notebook','Personal Laptop','AQ Gen X','Premium Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4520110508','PC','Notebook','Personal Laptop','AQ Gen X','Premium Misty Green');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4620110601','PC','Notebook','Personal Laptop','AQ Gen Y','Standard Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4620110602','PC','Notebook','Personal Laptop','AQ Gen Y','Standard Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4620110603','PC','Notebook','Personal Laptop','AQ Gen Y','Standard Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4620110604','PC','Notebook','Personal Laptop','AQ Gen Y','Plus Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4620110605','PC','Notebook','Personal Laptop','AQ Gen Y','Plus Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4620110606','PC','Notebook','Personal Laptop','AQ Gen Y','Plus Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4620110607','PC','Notebook','Personal Laptop','AQ Gen Y','Premium Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4620110608','PC','Notebook','Personal Laptop','AQ Gen Y','Premium Misty Green');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4720110701','PC','Notebook','Personal Laptop','AQ GEN Z','Standard Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4720110702','PC','Notebook','Personal Laptop','AQ GEN Z','Standard Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4721110703','PC','Notebook','Personal Laptop','AQ GEN Z','Standard Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4721110704','PC','Notebook','Personal Laptop','AQ GEN Z','Plus Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4721110705','PC','Notebook','Personal Laptop','AQ GEN Z','Plus Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4721110706','PC','Notebook','Personal Laptop','AQ GEN Z','Plus Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4721110707','PC','Notebook','Personal Laptop','AQ GEN Z','Premium Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4721110708','PC','Notebook','Personal Laptop','AQ GEN Z','Premium Misty Green');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4821110801','PC','Notebook','Personal Laptop','AQ F16','Standard Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4821110802','PC','Notebook','Personal Laptop','AQ F16','Standard Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4821110803','PC','Notebook','Personal Laptop','AQ F16','Standard Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4821110804','PC','Notebook','Personal Laptop','AQ F16','Plus Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4821110805','PC','Notebook','Personal Laptop','AQ F16','Plus Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4821110806','PC','Notebook','Personal Laptop','AQ F16','Plus Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4821110807','PC','Notebook','Personal Laptop','AQ F16','Premium Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4821110808','PC','Notebook','Personal Laptop','AQ F16','Premium Misty Green');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4918110101','PC','Notebook','Business Laptop','AQ BZ 101','Standard Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4918110102','PC','Notebook','Business Laptop','AQ BZ 101','Standard Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4918110103','PC','Notebook','Business Laptop','AQ BZ 101','Premium Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A4918110104','PC','Notebook','Business Laptop','AQ BZ 101','Premium Misty Green');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5018110201','PC','Notebook','Business Laptop','AQ BZ Compact','Standard Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5018110202','PC','Notebook','Business Laptop','AQ BZ Compact','Standard Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5018110203','PC','Notebook','Business Laptop','AQ BZ Compact','Standard Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5018110204','PC','Notebook','Business Laptop','AQ BZ Compact','Plus Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5018110205','PC','Notebook','Business Laptop','AQ BZ Compact','Plus Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5018110206','PC','Notebook','Business Laptop','AQ BZ Compact','Plus Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5018110207','PC','Notebook','Business Laptop','AQ BZ Compact','Premium Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5019110208','PC','Notebook','Business Laptop','AQ BZ Compact','Premium Misty Green');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5119110301','PC','Notebook','Business Laptop','AQ BZ Gen Y','Standard Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5119110302','PC','Notebook','Business Laptop','AQ BZ Gen Y','Standard Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5119110303','PC','Notebook','Business Laptop','AQ BZ Gen Y','Standard Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5119110304','PC','Notebook','Business Laptop','AQ BZ Gen Y','Plus Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5119110305','PC','Notebook','Business Laptop','AQ BZ Gen Y','Plus Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5119110306','PC','Notebook','Business Laptop','AQ BZ Gen Y','Plus Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5119110307','PC','Notebook','Business Laptop','AQ BZ Gen Y','Premium Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5119110308','PC','Notebook','Business Laptop','AQ BZ Gen Y','Premium Misty Green');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5219110401','PC','Notebook','Business Laptop','AQ BZ Gen Z','Standard Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5219110402','PC','Notebook','Business Laptop','AQ BZ Gen Z','Standard Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5219110403','PC','Notebook','Business Laptop','AQ BZ Gen Z','Standard Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5219110404','PC','Notebook','Business Laptop','AQ BZ Gen Z','Plus Grey');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5219110405','PC','Notebook','Business Laptop','AQ BZ Gen Z','Plus Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5219110406','PC','Notebook','Business Laptop','AQ BZ Gen Z','Plus Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5219110407','PC','Notebook','Business Laptop','AQ BZ Gen Z','Premium Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5220110408','PC','Notebook','Business Laptop','AQ BZ Gen Z','Premium Misty Green');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5318110101','PC','Notebook','Gaming Laptop','AQ Gamer 1','Standard Firey Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5318110102','PC','Notebook','Gaming Laptop','AQ Gamer 1','Standard Cool Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5318110103','PC','Notebook','Gaming Laptop','AQ Gamer 1','Standard Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5318110104','PC','Notebook','Gaming Laptop','AQ Gamer 1','Plus Firey Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5318110105','PC','Notebook','Gaming Laptop','AQ Gamer 1','Plus Cool Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5318110106','PC','Notebook','Gaming Laptop','AQ Gamer 1','Plus Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5318110107','PC','Notebook','Gaming Laptop','AQ Gamer 1','Premium Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5318110108','PC','Notebook','Gaming Laptop','AQ Gamer 1','Premium Misty Green');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5419110201','PC','Notebook','Gaming Laptop','AQ Gamer 2','Standard Firey Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5419110202','PC','Notebook','Gaming Laptop','AQ Gamer 2','Standard Cool Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5419110203','PC','Notebook','Gaming Laptop','AQ Gamer 2','Standard Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5419110204','PC','Notebook','Gaming Laptop','AQ Gamer 2','Plus Firey Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5419110205','PC','Notebook','Gaming Laptop','AQ Gamer 2','Plus Cool Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5419110206','PC','Notebook','Gaming Laptop','AQ Gamer 2','Plus Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5419110207','PC','Notebook','Gaming Laptop','AQ Gamer 2','Premium Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5419110208','PC','Notebook','Gaming Laptop','AQ Gamer 2','Premium Misty Green');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5519110301','PC','Notebook','Gaming Laptop','AQ Gamer 3','Standard Firey Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5519110302','PC','Notebook','Gaming Laptop','AQ Gamer 3','Standard Cool Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5519110303','PC','Notebook','Gaming Laptop','AQ Gamer 3','Standard Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5519110304','PC','Notebook','Gaming Laptop','AQ Gamer 3','Plus Firey Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5520110305','PC','Notebook','Gaming Laptop','AQ Gamer 3','Plus Cool Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5520110306','PC','Notebook','Gaming Laptop','AQ Gamer 3','Plus Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5520110307','PC','Notebook','Gaming Laptop','AQ Gamer 3','Premium Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5520110308','PC','Notebook','Gaming Laptop','AQ Gamer 3','Premium Misty Green');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5620110401','PC','Notebook','Gaming Laptop','AQ Smash 1','Standard Firey Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5620110402','PC','Notebook','Gaming Laptop','AQ Smash 1','Standard Cool Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5621110403','PC','Notebook','Gaming Laptop','AQ Smash 1','Standard Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5621110404','PC','Notebook','Gaming Laptop','AQ Smash 1','Plus Firey Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5621110405','PC','Notebook','Gaming Laptop','AQ Smash 1','Plus Cool Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5621110406','PC','Notebook','Gaming Laptop','AQ Smash 1','Plus Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5621110407','PC','Notebook','Gaming Laptop','AQ Smash 1','Premium Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5621110408','PC','Notebook','Gaming Laptop','AQ Smash 1','Premium Misty Green');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5721110501','PC','Notebook','Gaming Laptop','AQ Smash 2','Standard Firey Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5721110502','PC','Notebook','Gaming Laptop','AQ Smash 2','Standard Cool Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5721110503','PC','Notebook','Gaming Laptop','AQ Smash 2','Standard Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5721110504','PC','Notebook','Gaming Laptop','AQ Smash 2','Plus Firey Red');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5721110505','PC','Notebook','Gaming Laptop','AQ Smash 2','Plus Cool Blue');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5721110506','PC','Notebook','Gaming Laptop','AQ Smash 2','Plus Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5721110507','PC','Notebook','Gaming Laptop','AQ Smash 2','Premium Black');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5721110508','PC','Notebook','Gaming Laptop','AQ Smash 2','Premium Misty Green');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5820110101','PC','Desktop','Business Laptop','AQ BZ Allin1','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5820110102','PC','Desktop','Business Laptop','AQ BZ Allin1','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5820110103','PC','Desktop','Business Laptop','AQ BZ Allin1','Standard 3');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5820110104','PC','Desktop','Business Laptop','AQ BZ Allin1','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5820110105','PC','Desktop','Business Laptop','AQ BZ Allin1','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5820110106','PC','Desktop','Business Laptop','AQ BZ Allin1','Plus 3');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5820110107','PC','Desktop','Business Laptop','AQ BZ Allin1','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5821110108','PC','Desktop','Business Laptop','AQ BZ Allin1','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5921110201','PC','Desktop','Business Laptop','AQ BZ Allin1 Gen 2','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5921110202','PC','Desktop','Business Laptop','AQ BZ Allin1 Gen 2','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5921110203','PC','Desktop','Business Laptop','AQ BZ Allin1 Gen 2','Standard 3');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5921110204','PC','Desktop','Business Laptop','AQ BZ Allin1 Gen 2','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5921110205','PC','Desktop','Business Laptop','AQ BZ Allin1 Gen 2','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5921110206','PC','Desktop','Business Laptop','AQ BZ Allin1 Gen 2','Plus 3');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5921110207','PC','Desktop','Business Laptop','AQ BZ Allin1 Gen 2','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A5921110208','PC','Desktop','Business Laptop','AQ BZ Allin1 Gen 2','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6018110101','PC','Desktop','Personal Desktop','AQ Home Allin1','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6018110102','PC','Desktop','Personal Desktop','AQ Home Allin1','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6018110103','PC','Desktop','Personal Desktop','AQ Home Allin1','Standard 3');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6018110104','PC','Desktop','Personal Desktop','AQ Home Allin1','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6018110105','PC','Desktop','Personal Desktop','AQ Home Allin1','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6018110106','PC','Desktop','Personal Desktop','AQ Home Allin1','Plus 3');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6019110107','PC','Desktop','Personal Desktop','AQ Home Allin1','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6019110108','PC','Desktop','Personal Desktop','AQ Home Allin1','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6119110201','PC','Desktop','Personal Desktop','AQ HOME Allin1 Gen 2','Standard 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6119110202','PC','Desktop','Personal Desktop','AQ HOME Allin1 Gen 2','Standard 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6119110203','PC','Desktop','Personal Desktop','AQ HOME Allin1 Gen 2','Standard 3');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6119110204','PC','Desktop','Personal Desktop','AQ HOME Allin1 Gen 2','Plus 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6120110205','PC','Desktop','Personal Desktop','AQ HOME Allin1 Gen 2','Plus 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6120110206','PC','Desktop','Personal Desktop','AQ HOME Allin1 Gen 2','Plus 3');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6120110207','PC','Desktop','Personal Desktop','AQ HOME Allin1 Gen 2','Premium 1');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6121110208','PC','Desktop','Personal Desktop','AQ HOME Allin1 Gen 2','Premium 2');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6218160101','N & S','Storage','External Solid State Drives','AQ Digit SSD','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6218160102','N & S','Storage','External Solid State Drives','AQ Digit SSD','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6219160103','N & S','Storage','External Solid State Drives','AQ Digit SSD','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6319160201','N & S','Storage','External Solid State Drives','AQ Neuer SSD','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6319160202','N & S','Storage','External Solid State Drives','AQ Neuer SSD','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6319160203','N & S','Storage','External Solid State Drives','AQ Neuer SSD','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6419160301','N & S','Storage','External Solid State Drives','AQ Clx1','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6419160302','N & S','Storage','External Solid State Drives','AQ Clx1','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6419160303','N & S','Storage','External Solid State Drives','AQ Clx1','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6519160401','N & S','Storage','External Solid State Drives','AQ Clx2','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6520160402','N & S','Storage','External Solid State Drives','AQ Clx2','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6520160403','N & S','Storage','External Solid State Drives','AQ Clx2','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6620160501','N & S','Storage','External Solid State Drives','AQ Clx3','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6620160502','N & S','Storage','External Solid State Drives','AQ Clx3','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6621160503','N & S','Storage','External Solid State Drives','AQ Clx3','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6718160102','N & S','Storage','USB Flash Drives','AQ Pen Drive 2 IN 1','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6719160101','N & S','Storage','USB Flash Drives','AQ Pen Drive 2 IN 1','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6720160103','N & S','Storage','USB Flash Drives','AQ Pen Drive 2 IN 1','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6818160201','N & S','Storage','USB Flash Drives','AQ Pen Drive DRC','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6818160202','N & S','Storage','USB Flash Drives','AQ Pen Drive DRC','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6819160203','N & S','Storage','USB Flash Drives','AQ Pen Drive DRC','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6918160303','N & S','Storage','USB Flash Drives','AQ Ultra Dual 2.0','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6919160302','N & S','Storage','USB Flash Drives','AQ Ultra Dual 2.0','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A6921160301','N & S','Storage','USB Flash Drives','AQ Ultra Dual 2.0','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A7018160402','N & S','Storage','USB Flash Drives','AQ Ultra Dual 3.0','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A7019160401','N & S','Storage','USB Flash Drives','AQ Ultra Dual 3.0','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A7020160403','N & S','Storage','USB Flash Drives','AQ Ultra Dual 3.0','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A7118160101','N & S','Networking','Wi fi extender','AQ Wi Power Dx1','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A7119160102','N & S','Networking','Wi fi extender','AQ Wi Power Dx1','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A7119160103','N & S','Networking','Wi fi extender','AQ Wi Power Dx1','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A7219160201','N & S','Networking','Wi fi extender','AQ Wi Power Dx2','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A7220160202','N & S','Networking','Wi fi extender','AQ Wi Power Dx2','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A7220160203','N & S','Networking','Wi fi extender','AQ Wi Power Dx2','Premium');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A7321160301','N & S','Networking','Wi fi extender','AQ Wi Power Dx3','Standard');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A7321160302','N & S','Networking','Wi fi extender','AQ Wi Power Dx3','Plus');
INSERT INTO `` (`product_code`,`division`,`segment`,`category`,`product`,`variant`) VALUES ('A7321160303','N & S','Networking','Wi fi extender','AQ Wi Power Dx3','Premium');
